package drawio

import (
	"encoding/xml"
	"fmt"
	"io"
	"math"
	"strconv"
	"strings"

	"ai-agent-scaffold/internal/domain/validation"
)

const validatorName = "drawio-xml"

// Validator validates the uncompressed, single-page Draw.io XML generated by
// the current drawing workflow.
type Validator struct{}

func NewValidator() *Validator {
	return &Validator{}
}

func (*Validator) Name() string {
	return validatorName
}

// Validate 先完成 XML 语法解析，再执行 Draw.io 领域规则。
// 两步分开可以让调用方区分“XML 本身损坏”和“XML 能解析但图结构不符合约定”。
func (*Validator) Validate(output string) validation.Result {
	root, parseIssues := parseDocument(output)
	if len(parseIssues) > 0 {
		return failed(parseIssues)
	}

	issues := validateMXFile(root)
	return validation.Result{Passed: len(issues) == 0, Issues: issues}
}

type xmlNode struct {
	Name     xml.Name
	Attrs    []xml.Attr
	Children []*xmlNode
	Text     strings.Builder
}

// parseDocument 用栈把 XML token 还原成轻量树。这里不直接反序列化成固定结构，
// 是为了保留未知节点并把“不支持的 Draw.io 格式”报告为明确问题。
func parseDocument(input string) (*xmlNode, []validation.Issue) {
	if strings.TrimSpace(input) == "" {
		return nil, oneIssue("empty_document", "Draw.io output is empty", "/")
	}

	decoder := xml.NewDecoder(strings.NewReader(input))
	decoder.Strict = true

	var root *xmlNode
	stack := make([]*xmlNode, 0, 8)

	for {
		token, err := decoder.Token()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, oneIssue("invalid_xml", err.Error(), "/")
		}

		switch current := token.(type) {
		case xml.StartElement:
			node := &xmlNode{Name: current.Name, Attrs: current.Attr}
			if len(stack) == 0 {
				if root != nil {
					return nil, oneIssue("multiple_documents", "output must contain exactly one XML root element", "/")
				}
				root = node
			} else {
				parent := stack[len(stack)-1]
				parent.Children = append(parent.Children, node)
			}
			stack = append(stack, node)

		case xml.EndElement:
			if len(stack) > 0 {
				stack = stack[:len(stack)-1]
			}

		case xml.CharData:
			text := string(current)
			if len(stack) == 0 {
				if strings.TrimSpace(text) != "" {
					return nil, oneIssue("unexpected_document_content", "output contains text outside the XML root element", "/")
				}
				continue
			}
			stack[len(stack)-1].Text.WriteString(text)
		}
	}

	if root == nil {
		return nil, oneIssue("empty_document", "Draw.io output has no XML root element", "/")
	}
	return root, nil
}

// validateMXFile 固定第一版支持的结构契约：单页、未压缩、mxGraphModel 内只有一棵 root。
// 多页或压缩格式会明确拒绝，避免 Validator 没检查到内容却错误放行。
func validateMXFile(mxfile *xmlNode) []validation.Issue {
	if mxfile.Name.Local != "mxfile" {
		return oneIssue("invalid_root", "root element must be mxfile", "/"+mxfile.Name.Local)
	}

	diagrams := directChildren(mxfile, "diagram")
	if len(diagrams) == 0 {
		return oneIssue("missing_diagram", "mxfile must contain one diagram element", "/mxfile")
	}
	if len(diagrams) > 1 {
		return oneIssue("unsupported_multi_page", "only one diagram page is supported in the current workflow", "/mxfile")
	}

	diagram := diagrams[0]
	models := directChildren(diagram, "mxGraphModel")
	if len(models) == 0 {
		if strings.TrimSpace(diagram.Text.String()) != "" {
			return oneIssue("unsupported_compressed_diagram", "compressed diagram content is not supported; return an uncompressed mxGraphModel", "/mxfile/diagram[1]")
		}
		return oneIssue("missing_graph_model", "diagram must contain one mxGraphModel element", "/mxfile/diagram[1]")
	}
	if len(models) > 1 {
		return oneIssue("multiple_graph_models", "diagram must contain exactly one mxGraphModel element", "/mxfile/diagram[1]")
	}

	roots := directChildren(models[0], "root")
	if len(roots) != 1 {
		return oneIssue("invalid_graph_root", "mxGraphModel must contain exactly one root element", "/mxfile/diagram[1]/mxGraphModel")
	}
	return validateCells(roots[0])
}

type cellRecord struct {
	node *xmlNode
	id   string
	path string
}

// validateCells 采用两阶段校验。第一阶段收集完整 ID 集合，第二阶段再查引用，
// 因此 source/target 可以指向 XML 中后出现的节点，不会因元素顺序产生误报。
func validateCells(root *xmlNode) []validation.Issue {
	issues := make([]validation.Issue, 0)
	cells := make([]cellRecord, 0, len(root.Children))
	ids := make(map[string]struct{}, len(root.Children))

	// 第一遍只建立元素清单和 ID 索引，并按文档顺序记录结构问题。
	for index, child := range root.Children {
		path := fmt.Sprintf("/mxfile/diagram[1]/mxGraphModel/root/*[%d]", index+1)
		if child.Name.Local != "mxCell" {
			issues = append(issues, validation.Issue{
				Code:    "unsupported_cell_wrapper",
				Message: fmt.Sprintf("root child %q is not supported; mxCell elements must be direct children of root", child.Name.Local),
				Path:    path,
			})
			continue
		}

		id := strings.TrimSpace(attr(child, "id"))
		cellPath := path
		if id != "" {
			cellPath = fmt.Sprintf("/mxfile/diagram[1]/mxGraphModel/root/mxCell[id=%s]", id)
		}
		cells = append(cells, cellRecord{node: child, id: id, path: cellPath})

		if id == "" {
			issues = append(issues, validation.Issue{Code: "missing_id", Message: "mxCell id must be non-empty", Path: cellPath, Attribute: "id"})
			continue
		}
		if _, exists := ids[id]; exists {
			issues = append(issues, validation.Issue{Code: "duplicate_id", Message: fmt.Sprintf("mxCell id %q is duplicated", id), Path: cellPath, ElementID: id, Attribute: "id"})
			continue
		}
		ids[id] = struct{}{}
	}

	// 第二遍使用完整 ID 索引检查节点形状与 parent/source/target 引用。
	for _, cell := range cells {
		issues = append(issues, validateCellShape(cell)...)
		for _, reference := range []string{"parent", "source", "target"} {
			value := strings.TrimSpace(attr(cell.node, reference))
			if value == "" {
				continue
			}
			if _, exists := ids[value]; !exists {
				issues = append(issues, validation.Issue{
					Code:      "dangling_reference",
					Message:   fmt.Sprintf("%s references unknown mxCell id %q", reference, value),
					Path:      cell.path,
					ElementID: cell.id,
					Attribute: reference,
				})
			}
		}
	}
	return issues
}

// validateCellShape 只检查能确定判断的节点类型和基础 geometry。
// 布局美观、节点重叠和业务语义仍由后续 Reviewer 负责。
func validateCellShape(cell cellRecord) []validation.Issue {
	issues := make([]validation.Issue, 0)
	vertex := attr(cell.node, "vertex") == "1"
	edge := attr(cell.node, "edge") == "1"

	if vertex && edge {
		issues = append(issues, validation.Issue{Code: "conflicting_cell_kind", Message: "mxCell cannot be both a vertex and an edge", Path: cell.path, ElementID: cell.id})
	}
	if edge {
		for _, endpoint := range []string{"source", "target"} {
			if strings.TrimSpace(attr(cell.node, endpoint)) == "" {
				issues = append(issues, validation.Issue{Code: "missing_edge_endpoint", Message: fmt.Sprintf("edge mxCell must define %s", endpoint), Path: cell.path, ElementID: cell.id, Attribute: endpoint})
			}
		}
	}
	if !vertex {
		return issues
	}

	geometries := directChildren(cell.node, "mxGeometry")
	if len(geometries) != 1 {
		return append(issues, validation.Issue{Code: "invalid_vertex_geometry", Message: "vertex mxCell must contain exactly one mxGeometry element", Path: cell.path, ElementID: cell.id})
	}

	geometry := geometries[0]
	for _, dimension := range []string{"width", "height"} {
		value := strings.TrimSpace(attr(geometry, dimension))
		if !isPositiveFiniteNumber(value) {
			issues = append(issues, validation.Issue{Code: "invalid_geometry_dimension", Message: fmt.Sprintf("geometry %s must be a positive finite number", dimension), Path: cell.path + "/mxGeometry", ElementID: cell.id, Attribute: dimension})
		}
	}
	for _, coordinate := range []string{"x", "y"} {
		value := strings.TrimSpace(attr(geometry, coordinate))
		if value != "" && !isFiniteNumber(value) {
			issues = append(issues, validation.Issue{Code: "invalid_geometry_coordinate", Message: fmt.Sprintf("geometry %s must be a finite number when present", coordinate), Path: cell.path + "/mxGeometry", ElementID: cell.id, Attribute: coordinate})
		}
	}
	return issues
}

func directChildren(node *xmlNode, localName string) []*xmlNode {
	children := make([]*xmlNode, 0)
	for _, child := range node.Children {
		if child.Name.Local == localName {
			children = append(children, child)
		}
	}
	return children
}

func attr(node *xmlNode, name string) string {
	for _, item := range node.Attrs {
		if item.Name.Local == name {
			return item.Value
		}
	}
	return ""
}

func isPositiveFiniteNumber(value string) bool {
	number, ok := finiteNumber(value)
	return ok && number > 0
}

func isFiniteNumber(value string) bool {
	_, ok := finiteNumber(value)
	return ok
}

func finiteNumber(value string) (float64, bool) {
	if value == "" {
		return 0, false
	}
	number, err := strconv.ParseFloat(value, 64)
	if err != nil || math.IsInf(number, 0) || math.IsNaN(number) {
		return 0, false
	}
	return number, true
}

func oneIssue(code, message, path string) []validation.Issue {
	return []validation.Issue{{Code: code, Message: message, Path: path}}
}

func failed(issues []validation.Issue) validation.Result {
	return validation.Result{Passed: false, Issues: issues}
}
